// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// to regenerate this file, run the `sentry config typegen` command
//
// changes to this file are gitignored! for intentional updates,
// be sure to force add your changes by running:
// git add -f static/app/types/features.tsx
//
// see implementation in `src/sentry/runner/commands/config.py`

export type Feature = /* typegen:start */string/* typegen:end */
