// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// to regenerate this file, run the `sentry config typegen` command
//
// changes to this file are ignored by git! if you are intentionally
// updating this file, be sure to track your changes by running:
// git update-index --no-assume-unchanged "static/app/types/features.tsx"
// git add .
// git update-index --assume-unchanged "static/app/types/features.tsx"
//
// see implementation in `src/sentry/runner/commands/config.py`

export type Feature = /* typegen:start */ string; /* typegen:end */
